CREATE TABLE "Grants".sourcedata
(
  grant_application_id character varying(10),
  grant_status character varying(10),
  sponsor_code character varying(10),
  grant_category_code character varying(10),
  contract_value_band character(1),
  start_date date,
  rfcd_code_1 character(6),
  rfcd_percentage_1 character varying(10),
  rfcd_code_2 character(6),
  rfcd_percentage_2 character varying(10),
  rfcd_code_3 character(6),
  rfcd_percentage_3 character varying(10),
  rfcd_code_4 character(6),
  rfcd_percentage_4 character varying(10),
  rfcd_code_5 character(6),
  rfcd_percentage_5 character varying(10),
  seo_code_1 character(6),
  seo_percentage_1 character varying(10),
  seo_code_2 character(6),
  seo_percentage_2 character varying(10),
  seo_code_3 character(6),
  seo_percentage_3 character varying(10),
  seo_code_4 character(6),
  seo_percentage_4 character varying(10),
  seo_code_5 character(6),
  seo_percentage_5 character varying(10),
  person_id_1 character varying(7),
  role_1 character varying(30),
  year_of_birth_1 character varying(10),
  country_of_birth_1 character varying(30),
  home_language_1 character varying(30),
  dept_no__1 character varying(8),
  faculty_no__1 character varying(8),
  with_phd_1 boolean,
  no__of_years_in_uni_at_time_of_grant_1 character varying(15),
  number_of_successful_grant_1 character varying(10),
  number_of_unsuccessful_grant_1 character varying(10),
  astar_1 character varying(10),
  a_1 character varying(10),
  b_1 character varying(10),
  c_1 character varying(10),
  person_id_2 character varying(7),
  role_2 character varying(30),
  year_of_birth_2 character varying(10),
  country_of_birth_2 character varying(30),
  home_language_2 character varying(30),
  dept_no__2 character varying(8),
  faculty_no__2 character varying(8),
  with_phd_2 boolean,
  no__of_years_in_uni_at_time_of_grant_2 character varying(15),
  number_of_successful_grant_2 character varying(10),
  number_of_unsuccessful_grant_2 character varying(10),
  astar_2 character varying(10),
  a_2 character varying(10),
  b_2 character varying(10),
  c_2 character varying(10),
  person_id_3 character varying(7),
  role_3 character varying(30),
  year_of_birth_3 character varying(10),
  country_of_birth_3 character varying(30),
  home_language_3 character varying(30),
  dept_no__3 character varying(8),
  faculty_no__3 character varying(8),
  with_phd_3 boolean,
  no__of_years_in_uni_at_time_of_grant_3 character varying(15),
  number_of_successful_grant_3 character varying(10),
  number_of_unsuccessful_grant_3 character varying(10),
  astar_3 character varying(10),
  a_3 character varying(10),
  b_3 character varying(10),
  c_3 character varying(10),
  person_id_4 character varying(7),
  role_4 character varying(30),
  year_of_birth_4 character varying(10),
  country_of_birth_4 character varying(30),
  home_language_4 character varying(30),
  dept_no__4 character varying(8),
  faculty_no__4 character varying(8),
  with_phd_4 boolean,
  no__of_years_in_uni_at_time_of_grant_4 character varying(15),
  number_of_successful_grant_4 character varying(10),
  number_of_unsuccessful_grant_4 character varying(10),
  astar_4 character varying(10),
  a_4 character varying(10),
  b_4 character varying(10),
  c_4 character varying(10),
  person_id_5 character varying(7),
  role_5 character varying(30),
  year_of_birth_5 character varying(10),
  country_of_birth_5 character varying(30),
  home_language_5 character varying(30),
  dept_no__5 character varying(8),
  faculty_no__5 character varying(8),
  with_phd_5 boolean,
  no__of_years_in_uni_at_time_of_grant_5 character varying(15),
  number_of_successful_grant_5 character varying(10),
  number_of_unsuccessful_grant_5 character varying(10),
  astar_5 character varying(10),
  a_5 character varying(10),
  b_5 character varying(10),
  c_5 character varying(10),
  person_id_6 character varying(7),
  role_6 character varying(30),
  year_of_birth_6 character varying(10),
  country_of_birth_6 character varying(30),
  home_language_6 character varying(30),
  dept_no__6 character varying(8),
  faculty_no__6 character varying(8),
  with_phd_6 boolean,
  no__of_years_in_uni_at_time_of_grant_6 character varying(15),
  number_of_successful_grant_6 character varying(10),
  number_of_unsuccessful_grant_6 character varying(10),
  astar_6 character varying(10),
  a_6 character varying(10),
  b_6 character varying(10),
  c_6 character varying(10),
  person_id_7 character varying(7),
  role_7 character varying(30),
  year_of_birth_7 character varying(10),
  country_of_birth_7 character varying(30),
  home_language_7 character varying(30),
  dept_no__7 character varying(8),
  faculty_no__7 character varying(8),
  with_phd_7 boolean,
  no__of_years_in_uni_at_time_of_grant_7 character varying(15),
  number_of_successful_grant_7 character varying(10),
  number_of_unsuccessful_grant_7 character varying(10),
  astar_7 character varying(10),
  a_7 character varying(10),
  b_7 character varying(10),
  c_7 character varying(10),
  person_id_8 character varying(7),
  role_8 character varying(30),
  year_of_birth_8 character varying(10),
  country_of_birth_8 character varying(30),
  home_language_8 character varying(30),
  dept_no__8 character varying(8),
  faculty_no__8 character varying(8),
  with_phd_8 boolean,
  no__of_years_in_uni_at_time_of_grant_8 character varying(15),
  number_of_successful_grant_8 character varying(10),
  number_of_unsuccessful_grant_8 character varying(10),
  astar_8 character varying(10),
  a_8 character varying(10),
  b_8 character varying(10),
  c_8 character varying(10),
  person_id_9 character varying(7),
  role_9 character varying(30),
  year_of_birth_9 character varying(10),
  country_of_birth_9 character varying(30),
  home_language_9 character varying(30),
  dept_no__9 character varying(8),
  faculty_no__9 character varying(8),
  with_phd_9 boolean,
  no__of_years_in_uni_at_time_of_grant_9 character varying(15),
  number_of_successful_grant_9 character varying(10),
  number_of_unsuccessful_grant_9 character varying(10),
  astar_9 character varying(10),
  a_9 character varying(10),
  b_9 character varying(10),
  c_9 character varying(10),
  person_id_10 character varying(7),
  role_10 character varying(30),
  year_of_birth_10 character varying(10),
  country_of_birth_10 character varying(30),
  home_language_10 character varying(30),
  dept_no__10 character varying(8),
  faculty_no__10 character varying(8),
  with_phd_10 boolean,
  no__of_years_in_uni_at_time_of_grant_10 character varying(15),
  number_of_successful_grant_10 character varying(10),
  number_of_unsuccessful_grant_10 character varying(10),
  astar_10 character varying(10),
  a_10 character varying(10),
  b_10 character varying(10),
  c_10 character varying(10),
  person_id_11 character varying(7),
  role_11 character varying(30),
  year_of_birth_11 character varying(10),
  country_of_birth_11 character varying(30),
  home_language_11 character varying(30),
  dept_no__11 character varying(8),
  faculty_no__11 character varying(8),
  with_phd_11 boolean,
  no__of_years_in_uni_at_time_of_grant_11 character varying(15),
  number_of_successful_grant_11 character varying(10),
  number_of_unsuccessful_grant_11 character varying(10),
  astar_11 character varying(10),
  a_11 character varying(10),
  b_11 character varying(10),
  c_11 character varying(10),
  person_id_12 character varying(7),
  role_12 character varying(30),
  year_of_birth_12 character varying(10),
  country_of_birth_12 character varying(30),
  home_language_12 character varying(30),
  dept_no__12 character varying(8),
  faculty_no__12 character varying(8),
  with_phd_12 boolean,
  no__of_years_in_uni_at_time_of_grant_12 character varying(15),
  number_of_successful_grant_12 character varying(10),
  number_of_unsuccessful_grant_12 character varying(10),
  astar_12 character varying(10),
  a_12 character varying(10),
  b_12 character varying(10),
  c_12 character varying(10),
  person_id_13 character varying(7),
  role_13 character varying(30),
  year_of_birth_13 character varying(10),
  country_of_birth_13 character varying(30),
  home_language_13 character varying(30),
  dept_no__13 character varying(8),
  faculty_no__13 character varying(8),
  with_phd_13 boolean,
  no__of_years_in_uni_at_time_of_grant_13 character varying(15),
  number_of_successful_grant_13 character varying(10),
  number_of_unsuccessful_grant_13 character varying(10),
  astar_13 character varying(10),
  a_13 character varying(10),
  b_13 character varying(10),
  c_13 character varying(10),
  person_id_14 character varying(7),
  role_14 character varying(30),
  year_of_birth_14 character varying(10),
  country_of_birth_14 character varying(30),
  home_language_14 character varying(30),
  dept_no__14 character varying(8),
  faculty_no__14 character varying(8),
  with_phd_14 boolean,
  no__of_years_in_uni_at_time_of_grant_14 character varying(15),
  number_of_successful_grant_14 character varying(10),
  number_of_unsuccessful_grant_14 character varying(10),
  astar_14 character varying(10),
  a_14 character varying(10),
  b_14 character varying(10),
  c_14 character varying(10),
  person_id_15 character varying(7),
  role_15 character varying(30),
  year_of_birth_15 character varying(10),
  country_of_birth_15 character varying(30),
  home_language_15 character varying(30),
  dept_no__15 character varying(8),
  faculty_no__15 character varying(8),
  with_phd_15 boolean,
  no__of_years_in_uni_at_time_of_grant_15 character varying(15),
  number_of_successful_grant_15 character varying(10),
  number_of_unsuccessful_grant_15 character varying(10),
  astar_15 character varying(10),
  a_15 character varying(10),
  b_15 character varying(10),
  c_15 character varying(10),
  "C_152" character varying(10)
);

copy sourcedata from '/home/bobbruno/Downloads/DSR/Kaggle Grants/sourcedata/unimelb_training2.csv'

CREATE TABLE "Grants".Investigators as
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_1::integer id_person,
  sourcedata.role_1 tx_role,
  sourcedata.year_of_birth_1::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_1, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_1, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__1, '0') id_dept, 
  coalesce(sourcedata.faculty_no__1, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_1, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_1, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_1::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_1::integer nu_fail_grants, 
  sourcedata.astar_1::integer nu_AStar_papers, 
  sourcedata.a_1::integer nu_A_papers, 
  sourcedata.b_1::integer nu_B_papers, 
  sourcedata.c_1::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_1, role_1, year_of_birth_1, country_of_birth_1, home_language_1, dept_no__1, 
        faculty_no__1, cast(with_phd_1 as char), no__of_years_in_uni_at_time_of_grant_1, number_of_successful_grant_1, number_of_unsuccessful_grant_1, astar_1, a_1, b_1, c_1)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_2::integer id_person,
  sourcedata.role_2 tx_role,
  sourcedata.year_of_birth_2::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_2, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_2, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__2, '0') id_dept, 
  coalesce(sourcedata.faculty_no__2, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_2, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_2, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_2::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_2::integer nu_fail_grants, 
  sourcedata.astar_2::integer nu_AStar_papers, 
  sourcedata.a_2::integer nu_A_papers, 
  sourcedata.b_2::integer nu_B_papers, 
  sourcedata.c_2::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_2, role_2, year_of_birth_2, country_of_birth_2, home_language_2, dept_no__2, 
        faculty_no__2, cast(with_phd_2 as char), no__of_years_in_uni_at_time_of_grant_2, number_of_successful_grant_2, number_of_unsuccessful_grant_2, astar_2, a_2, b_2, c_2)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_3::integer id_person,
  sourcedata.role_3 tx_role,
  sourcedata.year_of_birth_3::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_3, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_3, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__3, '0') id_dept, 
  coalesce(sourcedata.faculty_no__3, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_3, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_3, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_3::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_3::integer nu_fail_grants, 
  sourcedata.astar_3::integer nu_AStar_papers, 
  sourcedata.a_3::integer nu_A_papers, 
  sourcedata.b_3::integer nu_B_papers, 
  sourcedata.c_3::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_3, role_3, year_of_birth_3, country_of_birth_3, home_language_3, dept_no__3, 
        faculty_no__3, cast(with_phd_3 as char), no__of_years_in_uni_at_time_of_grant_3, number_of_successful_grant_3, number_of_unsuccessful_grant_3, astar_3, a_3, b_3, c_3)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_4::integer id_person,
  sourcedata.role_4 tx_role,
  sourcedata.year_of_birth_4::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_4, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_4, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__4, '0') id_dept, 
  coalesce(sourcedata.faculty_no__4, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_4, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_4, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_4::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_4::integer nu_fail_grants, 
  sourcedata.astar_4::integer nu_AStar_papers, 
  sourcedata.a_4::integer nu_A_papers, 
  sourcedata.b_4::integer nu_B_papers, 
  sourcedata.c_4::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_4, role_4, year_of_birth_4, country_of_birth_4, home_language_4, dept_no__4, 
        faculty_no__4, cast(with_phd_4 as char), no__of_years_in_uni_at_time_of_grant_4, number_of_successful_grant_4, number_of_unsuccessful_grant_4, astar_4, a_4, b_4, c_4)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_5::integer id_person,
  sourcedata.role_5 tx_role,
  sourcedata.year_of_birth_5::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_5, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_5, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__5, '0') id_dept, 
  coalesce(sourcedata.faculty_no__5, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_5, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_5, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_5::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_5::integer nu_fail_grants, 
  sourcedata.astar_5::integer nu_AStar_papers, 
  sourcedata.a_5::integer nu_A_papers, 
  sourcedata.b_5::integer nu_B_papers, 
  sourcedata.c_5::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_5, role_5, year_of_birth_5, country_of_birth_5, home_language_5, dept_no__5, 
        faculty_no__5, cast(with_phd_5 as char), no__of_years_in_uni_at_time_of_grant_5, number_of_successful_grant_5, number_of_unsuccessful_grant_5, astar_5, a_5, b_5, c_5)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_6::integer id_person,
  sourcedata.role_6 tx_role,
  sourcedata.year_of_birth_6::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_6, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_6, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__6, '0') id_dept, 
  coalesce(sourcedata.faculty_no__6, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_6, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_6, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_6::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_6::integer nu_fail_grants, 
  sourcedata.astar_6::integer nu_AStar_papers, 
  sourcedata.a_6::integer nu_A_papers, 
  sourcedata.b_6::integer nu_B_papers, 
  sourcedata.c_6::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_6, role_6, year_of_birth_6, country_of_birth_6, home_language_6, dept_no__6, 
        faculty_no__6, cast(with_phd_6 as char), no__of_years_in_uni_at_time_of_grant_6, number_of_successful_grant_6, number_of_unsuccessful_grant_6, astar_6, a_6, b_6, c_6)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_7::integer id_person,
  sourcedata.role_7 tx_role,
  sourcedata.year_of_birth_7::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_7, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_7, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__7, '0') id_dept, 
  coalesce(sourcedata.faculty_no__7, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_7, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_7, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_7::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_7::integer nu_fail_grants, 
  sourcedata.astar_7::integer nu_AStar_papers, 
  sourcedata.a_7::integer nu_A_papers, 
  sourcedata.b_7::integer nu_B_papers, 
  sourcedata.c_7::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_7, role_7, year_of_birth_7, country_of_birth_7, home_language_7, dept_no__7, 
        faculty_no__7, cast(with_phd_7 as char), no__of_years_in_uni_at_time_of_grant_7, number_of_successful_grant_7, number_of_unsuccessful_grant_7, astar_7, a_7, b_7, c_7)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_8::integer id_person,
  sourcedata.role_8 tx_role,
  sourcedata.year_of_birth_8::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_8, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_8, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__8, '0') id_dept, 
  coalesce(sourcedata.faculty_no__8, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_8, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_8, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_8::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_8::integer nu_fail_grants, 
  sourcedata.astar_8::integer nu_AStar_papers, 
  sourcedata.a_8::integer nu_A_papers, 
  sourcedata.b_8::integer nu_B_papers, 
  sourcedata.c_8::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_8, role_8, year_of_birth_8, country_of_birth_8, home_language_8, dept_no__8, 
        faculty_no__8, cast(with_phd_8 as char), no__of_years_in_uni_at_time_of_grant_8, number_of_successful_grant_8, number_of_unsuccessful_grant_8, astar_8, a_8, b_8, c_8)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_9::integer id_person,
  sourcedata.role_9 tx_role,
  sourcedata.year_of_birth_9::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_9, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_9, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__9, '0') id_dept, 
  coalesce(sourcedata.faculty_no__9, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_9, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_9, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_9::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_9::integer nu_fail_grants, 
  sourcedata.astar_9::integer nu_AStar_papers, 
  sourcedata.a_9::integer nu_A_papers, 
  sourcedata.b_9::integer nu_B_papers, 
  sourcedata.c_9::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_9, role_9, year_of_birth_9, country_of_birth_9, home_language_9, dept_no__9, 
        faculty_no__9, cast(with_phd_9 as char), no__of_years_in_uni_at_time_of_grant_9, number_of_successful_grant_9, number_of_unsuccessful_grant_9, astar_9, a_9, b_9, c_9)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_10::integer id_person,
  sourcedata.role_10 tx_role,
  sourcedata.year_of_birth_10::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_10, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_10, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__10, '0') id_dept, 
  coalesce(sourcedata.faculty_no__10, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_10, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_10, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_10::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_10::integer nu_fail_grants, 
  sourcedata.astar_10::integer nu_AStar_papers, 
  sourcedata.a_10::integer nu_A_papers, 
  sourcedata.b_10::integer nu_B_papers, 
  sourcedata.c_10::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_10, role_10, year_of_birth_10, country_of_birth_10, home_language_10, dept_no__10, 
        faculty_no__10, cast(with_phd_10 as char), no__of_years_in_uni_at_time_of_grant_10, number_of_successful_grant_10, number_of_unsuccessful_grant_10, astar_10, a_10, b_10, c_10)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_11::integer id_person,
  sourcedata.role_11 tx_role,
  sourcedata.year_of_birth_11::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_11, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_11, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__11, '0') id_dept, 
  coalesce(sourcedata.faculty_no__11, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_11, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_11, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_11::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_11::integer nu_fail_grants, 
  sourcedata.astar_11::integer nu_AStar_papers, 
  sourcedata.a_11::integer nu_A_papers, 
  sourcedata.b_11::integer nu_B_papers, 
  sourcedata.c_11::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_11, role_11, year_of_birth_11, country_of_birth_11, home_language_11, dept_no__11, 
        faculty_no__11, cast(with_phd_11 as char), no__of_years_in_uni_at_time_of_grant_11, number_of_successful_grant_11, number_of_unsuccessful_grant_11, astar_11, a_11, b_11, c_11)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_12::integer id_person,
  sourcedata.role_12 tx_role,
  sourcedata.year_of_birth_12::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_12, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_12, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__12, '0') id_dept, 
  coalesce(sourcedata.faculty_no__12, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_12, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_12, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_12::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_12::integer nu_fail_grants, 
  sourcedata.astar_12::integer nu_AStar_papers, 
  sourcedata.a_12::integer nu_A_papers, 
  sourcedata.b_12::integer nu_B_papers, 
  sourcedata.c_12::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_12, role_12, year_of_birth_12, country_of_birth_12, home_language_12, dept_no__12, 
        faculty_no__12, cast(with_phd_12 as char), no__of_years_in_uni_at_time_of_grant_12, number_of_successful_grant_12, number_of_unsuccessful_grant_12, astar_12, a_12, b_12, c_12)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_13::integer id_person,
  sourcedata.role_13 tx_role,
  sourcedata.year_of_birth_13::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_13, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_13, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__13, '0') id_dept, 
  coalesce(sourcedata.faculty_no__13, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_13, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_13, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_13::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_13::integer nu_fail_grants, 
  sourcedata.astar_13::integer nu_AStar_papers, 
  sourcedata.a_13::integer nu_A_papers, 
  sourcedata.b_13::integer nu_B_papers, 
  sourcedata.c_13::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_13, role_13, year_of_birth_13, country_of_birth_13, home_language_13, dept_no__13, 
        faculty_no__13, cast(with_phd_13 as char), no__of_years_in_uni_at_time_of_grant_13, number_of_successful_grant_13, number_of_unsuccessful_grant_13, astar_13, a_13, b_13, c_13)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_14::integer id_person,
  sourcedata.role_14 tx_role,
  sourcedata.year_of_birth_14::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_14, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_14, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__14, '0') id_dept, 
  coalesce(sourcedata.faculty_no__14, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_14, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_14, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_14::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_14::integer nu_fail_grants, 
  sourcedata.astar_14::integer nu_AStar_papers, 
  sourcedata.a_14::integer nu_A_papers, 
  sourcedata.b_14::integer nu_B_papers, 
  sourcedata.c_14::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_14, role_14, year_of_birth_14, country_of_birth_14, home_language_14, dept_no__14, 
        faculty_no__14, cast(with_phd_14 as char), no__of_years_in_uni_at_time_of_grant_14, number_of_successful_grant_14, number_of_unsuccessful_grant_14, astar_14, a_14, b_14, c_14)  is not null
union
SELECT 
  sourcedata.grant_application_id::integer id_application,
  1 as nu_investigator,
  sourcedata.person_id_15::integer id_person,
  sourcedata.role_15 tx_role,
  sourcedata.year_of_birth_15::integer nu_birth_year, 
  coalesce(sourcedata.country_of_birth_15, 'Unknown') tx_country_birth, 
  coalesce(sourcedata.home_language_15, 'Unknown') tx_language, 
  coalesce(sourcedata.dept_no__15, '0') id_dept, 
  coalesce(sourcedata.faculty_no__15, '0') nu_faculty, 
  coalesce(sourcedata.with_phd_15, False) bo_phd, 
  coalesce(sourcedata.no__of_years_in_uni_at_time_of_grant_15, 'Unknown') tx_years_in_univ_range, 
  sourcedata.number_of_successful_grant_15::integer nu_succ_grants, 
  sourcedata.number_of_unsuccessful_grant_15::integer nu_fail_grants, 
  sourcedata.astar_15::integer nu_AStar_papers, 
  sourcedata.a_15::integer nu_A_papers, 
  sourcedata.b_15::integer nu_B_papers, 
  sourcedata.c_15::integer nu_C_papers
FROM "Grants".sourcedata
  WHERE coalesce(person_id_15, role_15, year_of_birth_15, country_of_birth_15, home_language_15, dept_no__15, 
        faculty_no__15, cast(with_phd_15 as char), no__of_years_in_uni_at_time_of_grant_15, number_of_successful_grant_15, number_of_unsuccessful_grant_15, astar_15, a_15, b_15, c_15)  is not null;
        
UPDATE "Grants".investigators set id_person = 0 where id_person is null;

commit;

ALTER TABLE "Grants".investigators
  ADD CONSTRAINT "PK_INVESTIGATORS" PRIMARY KEY(id_application, nu_investigator, id_person);
CREATE INDEX "IX1_Investigators"
  ON "Grants".investigators
  USING btree
  (id_application, id_person);

alter table "Grants".investigators add column short_role varchar(3);
update "Grants".investigators set short_role = 'ECI' where tx_role = 'EXT_CHIEF_INVESTIGATOR';
update "Grants".investigators set short_role = 'SCI' where tx_role = 'STUD_CHIEF_INVESTIGATOR';
update "Grants".investigators set short_role = 'CI' where tx_role = 'CHIEF_INVESTIGATOR';
update "Grants".investigators set short_role = 'DR' where tx_role = 'DELEGATED_RESEARCHER';
update "Grants".investigators set short_role = 'EA' where tx_role = 'EXTERNAL_ADVISOR';
update "Grants".investigators set short_role = 'HV' where tx_role = 'HONVISIT';
update "Grants".investigators set short_role = 'PS' where tx_role = 'PRINCIPAL_SUPERVISOR';
update "Grants".investigators set short_role = 'SR' where tx_role = 'STUDRES';
update "Grants".investigators set short_role = 'UNK' where tx_role is null;
commit;

  